/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import JobPackage.*;
import java.sql.*;
import javax.swing.JMenuItem;
import java.util.ArrayList;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author Alexis
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    private ArrayList<JMenuItem> MapList;
    private MappingMap mapping;
    private int i;
    private ArrayList<String> Names;
    private ArrayList<Integer> IDs;
    
    
    private Graphics g = null;
    private Image img;
    
    public Window() {
        initComponents();
        
        mapping = new MappingMap(); // objet MappingMap
        Names = new ArrayList<String>();
        IDs = new ArrayList<Integer>();
        MapList = new ArrayList<JMenuItem>();
        this.makeListOfMaps();
        this.showListOfMapsInMenuBar();
    }
    
    public void makeListOfMaps() { // RECUPERE LES INFOS SUR LES MAPS ET REMPLIE LES TABLEAUX
        ResultSet result =  mapping.getMap();
        try {

            while(result.next()) {

               Names.add(result.getString("MAP_NAME"));
               IDs.add(result.getInt("MAP_ID"));
             }

         } catch (Exception e) { System.out.println("makeListOfMaps a chié"); e.printStackTrace();}
    }
    
    public void showListOfMapsInMenuBar() {
         

        try {
        for(i = 0; i < IDs.size(); i++) {
            MapList.add(new JMenuItem(Names.get(i)));
            Menu_Lieux.add(MapList.get(i));
        }
        } catch(Exception e) {e.printStackTrace();}
        
        
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Map_Panel = new Panel_Picture();
        Research_Panel = new javax.swing.JPanel();
        SearchBar = new javax.swing.JTextField();
        Scroll_Research = new javax.swing.JScrollPane();
        Result_Research = new javax.swing.JTextArea();
        Navigation_Panel = new javax.swing.JPanel();
        Combo_Interface = new javax.swing.JComboBox();
        Button_AddPOI = new javax.swing.JButton();
        Button_DelPOI = new javax.swing.JButton();
        Button_Prev = new javax.swing.JButton();
        Button_Next = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jToolBar2 = new javax.swing.JToolBar();
        MenuBar = new javax.swing.JMenuBar();
        Menu_Lieux = new javax.swing.JMenu();
        Menu_POI = new javax.swing.JMenu();
        Menu_Help = new javax.swing.JMenu();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Map_Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout Map_PanelLayout = new javax.swing.GroupLayout(Map_Panel);
        Map_Panel.setLayout(Map_PanelLayout);
        Map_PanelLayout.setHorizontalGroup(
            Map_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );
        Map_PanelLayout.setVerticalGroup(
            Map_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        Research_Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        SearchBar.setText("Recherche");

        Result_Research.setColumns(20);
        Result_Research.setRows(5);
        Scroll_Research.setViewportView(Result_Research);

        javax.swing.GroupLayout Research_PanelLayout = new javax.swing.GroupLayout(Research_Panel);
        Research_Panel.setLayout(Research_PanelLayout);
        Research_PanelLayout.setHorizontalGroup(
            Research_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Research_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Research_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchBar)
                    .addComponent(Scroll_Research, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                .addContainerGap())
        );
        Research_PanelLayout.setVerticalGroup(
            Research_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Research_PanelLayout.createSequentialGroup()
                .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Scroll_Research))
        );

        Navigation_Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        Combo_Interface.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Button_AddPOI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Resources/addmark.PNG")));
        Button_AddPOI.setBorderPainted(false);
        Button_AddPOI.setContentAreaFilled(false);
        Button_AddPOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AddPOIActionPerformed(evt);
            }
        });

        Button_DelPOI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Resources/delmark.PNG")));
        Button_DelPOI.setBorderPainted(false);
        Button_DelPOI.setContentAreaFilled(false);

        Button_Prev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Resources/fleche_suivant.png")));
        Button_Prev.setBorderPainted(false);
        Button_Prev.setContentAreaFilled(false);

        Button_Next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Resources/fleche_precedent.png")));
        Button_Next.setBorderPainted(false);
        Button_Next.setContentAreaFilled(false);

        javax.swing.GroupLayout Navigation_PanelLayout = new javax.swing.GroupLayout(Navigation_Panel);
        Navigation_Panel.setLayout(Navigation_PanelLayout);
        Navigation_PanelLayout.setHorizontalGroup(
            Navigation_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Navigation_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Navigation_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Combo_Interface, 0, 297, Short.MAX_VALUE)
                    .addGroup(Navigation_PanelLayout.createSequentialGroup()
                        .addComponent(Button_AddPOI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_DelPOI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Prev, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Navigation_PanelLayout.setVerticalGroup(
            Navigation_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Navigation_PanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(Navigation_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Prev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_Next, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_AddPOI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_DelPOI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Combo_Interface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        jToolBar1.setRollover(true);
        jTabbedPane1.addTab("Consulter", jToolBar1);

        jToolBar2.setRollover(true);
        jTabbedPane1.addTab("Ajouter", jToolBar2);

        Menu_Lieux.setText("Lieux");
        MenuBar.add(Menu_Lieux);

        Menu_POI.setText("POI");
        MenuBar.add(Menu_POI);

        Menu_Help.setText("Help");
        MenuBar.add(Menu_Help);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Map_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Navigation_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Research_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Map_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Navigation_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Research_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_AddPOIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AddPOIActionPerformed
        // TODO add your handling code here:
      //  Information_Panel.setVisible(false);

    }//GEN-LAST:event_Button_AddPOIActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_AddPOI;
    private javax.swing.JButton Button_DelPOI;
    private javax.swing.JButton Button_Next;
    private javax.swing.JButton Button_Prev;
    private javax.swing.JComboBox Combo_Interface;
    private javax.swing.JPanel Map_Panel;
    private javax.swing.JMenuBar MenuBar;
    public javax.swing.JMenu Menu_Help;
    public javax.swing.JMenu Menu_Lieux;
    public javax.swing.JMenu Menu_POI;
    private javax.swing.JPanel Navigation_Panel;
    private javax.swing.JPanel Research_Panel;
    private javax.swing.JTextArea Result_Research;
    private javax.swing.JScrollPane Scroll_Research;
    public javax.swing.JTextField SearchBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
